### ISSUE TITLE
Commonref branch and Sorting branch not isolated

### ISSUE THREAD

**Issue by gdenfield** [atlab/sessions#5]
It looks like the commonref branch was made off of the sorting branch, after the sorting branch had diverged fairly significantly from master due to working on Utah array spike sorting code. It looks that way because the common ref branch has basically all of the changes that were made in the sorting branch.

I've got the silicon probe common ref subtraction code working and would like to initiate pull requests for those files but don't want to pull all those sorting branch changes into master along with it. How should I proceed?

**Comment by gdenfield** [comment]
I created a new branch called isocommonref off of the master branch and will just make the changes there, since they are minimal. We can delete the old 'commonref' branch

**Comment by aecker** [comment]
Usually the way you would do this is use `git rebase`. See e.g. http://git-scm.com/book/en/v2/Git-Branching-Rebasing (I think the part where it explains `git rebase --onto master server client` is the one that describes solves situation).
